Feat jlink upgrade (#856)
* Fix error when calling debug help

Call to debug help cli results in TypeSystemError

iotile hw --port=jlink connect_direct device=nrf52 debug help
TypeSystemError: Annotation specified for unknown parameter
Additional Information:
param: address

* Add missed parameter 'region' in write_memory debug cmd

* Refactor jlink_background.py and jlink.py

Remove JLinkControlThread.
Interact with jlink using executor in JLinkAsync.
Refactor Jlink to use StandartDeviceAdapter.
Add maintenance periodical task for polling control info.

* Update JlinkAdapter probe method

Jlink probe tries to find control info even when adapter is not connected
"scan" shows the device always, not only after "connect_direct"
It's possible to connect to the device using cmd "connect UUID"

* Jlink tracing and streaming (#832)

* Fix attempts check

Condition clause if i == max_attempts: would never be executed

* JlinkAdapter, add tracing and streaming support

* Fixed forensic tool after jlink upgrade

* Fixes

* Refactor to read multiple frames at once

* Fix jlink multiple frame read (#854)

* Refactor to read multiple frames at once

* Quick maths fix

* Allow run_execturo in finalizer

* Fixed connection issues/logic

* Remove comments

* Cleanup

* Fixed blank lines

* Add version to KNOWN_VERSIONS

* Cleanup

* Backwards compatibility check

Also cleanup

* Version bumps

* Version number fixes

* Updated error handling

* Changing to release candidate

* Add retry logic to JLink rpc

* Only catch external gate errors

* Fix the case where non HardwareError is thrown

* Re-raising exception

* Using dict for safety